# Generated by Django 6.1.1 on 2026-09-17 00:48

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intents', '0001_enable_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='codigo', max_length=100, unique=True)),
                ('system_action', models.CharField(db_column='acao_sistema', max_length=255)),
                ('description', models.TextField(db_column='descricao')),
            ],
            options={
                'db_table': 'INTENCAO',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='texto')),
                ('intention', models.ForeignKey(db_column='intencao_id', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intents.intention')),
            ],
            options={
                'db_table': 'RESPOSTA',
            },
        ),
        migrations.CreateModel(
            name='IntentionExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='texto')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('intention', models.ForeignKey(db_column='intencao_id', on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='intents.intention')),
            ],
            options={
                'db_table': 'EXEMPLO_INTENCAO',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='exemplo_intencao_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
