[pytest]
addopts = -vv -ra --tb=long
DJANGO_SETTINGS_MODULE = settings.settings
python_files = tests.py test_*.py *_tests.py

markers =
    unit: isolated tests without database or HTTP integration
    integration: tests exercising multiple components, such as HTTP views and the database
