# Generated by Django 6.1.1 on 2026-09-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityManagement', '0002_alter_atividade_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='conteudo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividade', to='activityManagement.conteudo'),
        ),
    ]
