# Generated by Django 6.1.1 on 2026-10-07 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityManagement', '0006_alter_atividade_modulo'),
        ('questionsManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resposta_fornecida', models.TextField(blank=True, null=True)),
                ('correta', models.BooleanField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_questoes', to='activityManagement.execucaoatividade')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_submetidas', to='questionsManagement.questao')),
            ],
            options={
                'db_table': 'RESPOSTA_QUESTAO',
                'indexes': [models.Index(fields=['execucao', 'correta'], name='RESPOSTA_QU_execuca_beb4d9_idx')],
            },
        ),
    ]
