# Generated by Django 6.1.1 on 2026-09-27 22:25

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intents', '0001_enable_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaCorpus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topico', models.CharField(max_length=100)),
                ('pergunta', models.CharField(max_length=255, unique=True)),
                ('resposta', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CORPUS_ENTRADA',
                'ordering': ['topico', 'pergunta'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaCorpus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('entrada', models.ForeignKey(db_column='entrada_id', on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='semanticSearch.entradacorpus')),
            ],
            options={
                'db_table': 'CORPUS_PERGUNTA',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='corpus_pergunta_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
