# Generated by Django 6.1.1 on 2026-09-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semanticSearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='perguntacorpus',
            name='corpus_pergunta_embedding_hnsw',
        ),
    ]
