# Generated by Django 6.1.1 on 2026-09-21 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_assistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SESSAO',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remetente', models.CharField(choices=[('USUARIO', 'Usuario'), ('ASSISTENTE', 'Assistente')], max_length=10)),
                ('conteudo', models.TextField()),
                ('distancia', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('intencao', models.ForeignKey(blank=True, db_column='intencao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='intents.intention')),
                ('sessao', models.ForeignKey(db_column='sessao_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='assistantManagement.sessao')),
            ],
            options={
                'db_table': 'MENSAGEM',
            },
        ),
        migrations.AddIndex(
            model_name='sessao',
            index=models.Index(fields=['usuario'], name='sessao_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['sessao'], name='mensagem_sessao_idx'),
        ),
    ]
