# Generated by Django 6.1.1 on 2026-09-27 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantManagement', '0001_initial'),
        ('trackManagement', '0002_create_pgvector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='trilha_contexto',
            field=models.ForeignKey(blank=True, db_column='trilha_contexto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_assistente', to='trackManagement.trilha'),
        ),
    ]
