# Generated by Django 6.1.1 on 2026-09-16 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('habilidade', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TRILHA',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='EM_ANDAMENTO', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='trackManagement.trilha')),
            ],
            options={
                'db_table': 'MATRICULA',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(max_length=30)),
                ('ordem_modulo', models.IntegerField(default=0)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='trackManagement.trilha')),
            ],
            options={
                'db_table': 'MODULO',
                'ordering': ['ordem_modulo'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='BLOQUEADO', max_length=30)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_modulos', to='trackManagement.matricula')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='trackManagement.modulo')),
            ],
            options={
                'db_table': 'PROGRESSO_MODULO',
                'constraints': [models.UniqueConstraint(fields=('matricula', 'modulo'), name='unique_matricula_modulo')],
            },
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('usuario', 'trilha'), name='unique_usuario_trilha'),
        ),
    ]
