# Generated by Django 6.1.1 on 2026-09-22 01:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activityManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_exercicio', models.CharField(max_length=30)),
                ('enunciado', models.TextField()),
                ('codigo_snippet', models.TextField(blank=True, default='')),
                ('gabarito_esperado', models.CharField(max_length=255)),
                ('explicacao', models.TextField(blank=True, default='')),
                ('dica_conceitual', models.TextField(blank=True, default='')),
                ('ordem_questao', models.IntegerField()),
                ('peso_pontuacao', models.IntegerField(default=10)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='activityManagement.atividade')),
            ],
            options={
                'db_table': 'QUESTAO',
                'ordering': ['ordem_questao'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoOpcao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto_opcao', models.TextField()),
                ('ordem', models.IntegerField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='questionsManagement.questao')),
            ],
            options={
                'db_table': 'QUESTAO_OPCAO',
                'ordering': ['ordem'],
            },
        ),
    ]
