# Generated by Django 6.1.1 on 2026-09-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_content_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='content',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='module',
        ),
        migrations.RemoveField(
            model_name='question',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
