# Generated by Django 6.1.1 on 2026-09-16 23:46

import django.utils.timezone
import uuid
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickName',
            new_name='apelido',
        ),
        migrations.AddField(
            model_name='user',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='streak_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xp_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RunSQL(
            sql="""
                CREATE TEMP TABLE user_id_map (
                    old_id bigint PRIMARY KEY,
                    new_id uuid NOT NULL
                );
        
                ALTER TABLE "userManagement_user"
                    ADD COLUMN "id_uuid" uuid;
        
                UPDATE "userManagement_user"
                SET "id_uuid" = gen_random_uuid();
        
                INSERT INTO user_id_map (old_id, new_id)
                SELECT id, id_uuid
                FROM "userManagement_user";
        
                ALTER TABLE "userManagement_user_groups"
                    DROP CONSTRAINT "userManagement_user__user_id_59fa3f6d_fk_userManag";
        
                ALTER TABLE "userManagement_user_user_permissions"
                    DROP CONSTRAINT "userManagement_user__user_id_96e387e8_fk_userManag";
        
                ALTER TABLE "django_admin_log"
                    DROP CONSTRAINT "django_admin_log_user_id_c564eba6_fk_userManagement_user_id";
        
                ALTER TABLE "userManagement_user_groups"
                    ADD COLUMN "user_id_uuid" uuid;
        
                UPDATE "userManagement_user_groups" g
                SET "user_id_uuid" = m.new_id
                FROM user_id_map m
                WHERE g.user_id = m.old_id;
        
                ALTER TABLE "userManagement_user_groups"
                    DROP COLUMN "user_id";
        
                ALTER TABLE "userManagement_user_groups"
                    RENAME COLUMN "user_id_uuid" TO "user_id";
        
                ALTER TABLE "userManagement_user_user_permissions"
                    ADD COLUMN "user_id_uuid" uuid;
        
                UPDATE "userManagement_user_user_permissions" p
                SET "user_id_uuid" = m.new_id
                FROM user_id_map m
                WHERE p.user_id = m.old_id;
        
                ALTER TABLE "userManagement_user_user_permissions"
                    DROP COLUMN "user_id";
        
                ALTER TABLE "userManagement_user_user_permissions"
                    RENAME COLUMN "user_id_uuid" TO "user_id";
        
                ALTER TABLE "django_admin_log"
                    ADD COLUMN "user_id_uuid" uuid;
        
                UPDATE "django_admin_log" a
                SET "user_id_uuid" = m.new_id
                FROM user_id_map m
                WHERE a.user_id = m.old_id;
        
                ALTER TABLE "django_admin_log"
                    DROP COLUMN "user_id";
        
                ALTER TABLE "django_admin_log"
                    RENAME COLUMN "user_id_uuid" TO "user_id";
        
                ALTER TABLE "userManagement_user"
                    DROP CONSTRAINT "userManagement_user_pkey";
        
                ALTER TABLE "userManagement_user"
                    DROP COLUMN "id";
        
                ALTER TABLE "userManagement_user"
                    RENAME COLUMN "id_uuid" TO "id";
        
                ALTER TABLE "userManagement_user"
                    ALTER COLUMN "id" SET NOT NULL,
                    ALTER COLUMN "id" SET DEFAULT gen_random_uuid(),
                    ADD PRIMARY KEY ("id");
        
                ALTER TABLE "userManagement_user_groups"
                    ADD CONSTRAINT "userManagement_user_groups_user_id_fk"
                    FOREIGN KEY ("user_id")
                    REFERENCES "userManagement_user" ("id")
                    DEFERRABLE INITIALLY DEFERRED;
        
                ALTER TABLE "userManagement_user_user_permissions"
                    ADD CONSTRAINT "userManagement_user_permissions_user_id_fk"
                    FOREIGN KEY ("user_id")
                    REFERENCES "userManagement_user" ("id")
                    DEFERRABLE INITIALLY DEFERRED;
        
                ALTER TABLE "django_admin_log"
                    ADD CONSTRAINT "django_admin_log_user_id_fk"
                    FOREIGN KEY ("user_id")
                    REFERENCES "userManagement_user" ("id")
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
