# Generated by Django 6.1.1 on 2026-10-08 00:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_user_is_primeiro_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'INTERESSE',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UsuarioInteresse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_interessados', to='userManagement.interesse')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USUARIO_INTERESSE',
                'unique_together': {('usuario', 'interesse')},
            },
        ),
    ]
